[project]
name = "lurkbait-fishing-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numbers-parser>=4.15.1",
    "sqlite-utils>=3.38",
]
